#!/bin/bash
# install_openhuman_memory.sh
# 
# Interactive installer: Wires OpenHuman into BROski-Obsidian-Brain
# Makes your vault the central memory store for OpenHuman + all agents
#
# Works on: Linux, macOS, Windows (WSL/Git Bash)
# Run: bash install_openhuman_memory.sh
#
# BROski♾️

set -e

# Colors for output (ADHD-friendly, clear & punchy)
RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${BLUE}╔════════════════════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║  🧠 OPENHUMAN → BROSKI-OBSIDIAN-BRAIN INTEGRATION INSTALLER      ║${NC}"
echo -e "${BLUE}╚════════════════════════════════════════════════════════════════╝${NC}"
echo ""

# 1. Detect OS
OS=$(uname -s)
case "$OS" in
  Linux*)   OS_TYPE="Linux";;
  Darwin*)  OS_TYPE="macOS";;
  MINGW*)   OS_TYPE="Windows";;
  MSYS*)    OS_TYPE="Windows";;
  *)        OS_TYPE="Unknown";;
esac

echo -e "${GREEN}✓${NC} Detected OS: ${YELLOW}$OS_TYPE${NC}"
echo ""

# 2. Find vault path
echo -e "${BLUE}Step 1: Locate your BROski-Obsidian-Brain vault${NC}"
echo ""

# Try to find it automatically
VAULT_SEARCH_PATHS=(
  "$HOME/BROski-Obsidian-Brain-for-HyperFocus-z0ne"
  "$HOME/HYPERFOCUSZONE/BROski-Obsidian-Brain-for-HyperFocus-z0ne"
  "$HOME/repos/BROski-Obsidian-Brain-for-HyperFocus-z0ne"
  "/home/*/BROski-Obsidian-Brain-for-HyperFocus-z0ne"
  "$(dirname "$0")"
  "$(pwd)"
)

VAULT_PATH=""
for path in "${VAULT_SEARCH_PATHS[@]}"; do
  if [ -d "$path/HYPERFOCUS_ZONE" ]; then
    VAULT_PATH="$path"
    echo -e "${GREEN}✓${NC} Found vault at: ${YELLOW}$VAULT_PATH${NC}"
    break
  fi
done

# If not found, ask user
if [ -z "$VAULT_PATH" ]; then
  echo -e "${YELLOW}⚠ Couldn't find vault automatically${NC}"
  echo "Enter the path to your BROski-Obsidian-Brain repo:"
  echo "(e.g., $HOME/BROski-Obsidian-Brain-for-HyperFocus-z0ne)"
  read -p "> " VAULT_PATH
fi

# Validate
if [ ! -d "$VAULT_PATH/HYPERFOCUS_ZONE" ]; then
  echo -e "${RED}✗ Error: $VAULT_PATH/HYPERFOCUS_ZONE not found${NC}"
  echo "Please check the path and try again."
  exit 1
fi

echo -e "${GREEN}✓${NC} Vault path confirmed: ${YELLOW}$VAULT_PATH${NC}"
echo ""

# 3. Create OpenHuman config directory
echo -e "${BLUE}Step 2: Set up OpenHuman config${NC}"
echo ""

case "$OS_TYPE" in
  Linux|macOS)
    OPENHUMAN_CONFIG="$HOME/.openhuman"
    ;;
  Windows)
    OPENHUMAN_CONFIG="$HOME/.openhuman"
    ;;
esac

mkdir -p "$OPENHUMAN_CONFIG"
echo -e "${GREEN}✓${NC} Config dir: ${YELLOW}$OPENHUMAN_CONFIG${NC}"
echo ""

# 4. Create .env file
echo -e "${BLUE}Step 3: Create OpenHuman .env${NC}"
echo ""

ENV_FILE="$OPENHUMAN_CONFIG/.env"

cat > "$ENV_FILE" << EOF
# OpenHuman ↔ BROski-Obsidian-Brain Integration
# Generated by install_openhuman_memory.sh
# Last updated: $(date -u +%Y-%m-%dT%H:%M:%SZ)

# Path to your vault (where OpenHuman writes .md files)
OPENHUMAN_WORKSPACE=$VAULT_PATH

# Memory backend (when available in OpenHuman binary)
# MEMORY_BACKEND=agentmemory
# MEMORY_AGENTMEMORY_DB=$VAULT_PATH/brain.db

# Optional: Enable debug logging
# DEBUG=1
EOF

echo -e "${GREEN}✓${NC} Created: ${YELLOW}$ENV_FILE${NC}"
cat "$ENV_FILE"
echo ""

# 5. Create symlink (Option A from plan)
echo -e "${BLUE}Step 4: Create symlink (Option A)${NC}"
echo ""
echo "This creates a live link from ~/.openhuman/memory → your vault's 00-Inbox"
echo "so OpenHuman's auto-synced notes flow straight into your vault."
echo ""

OPENHUMAN_MEMORY_DIR="$OPENHUMAN_CONFIG/memory"
VAULT_INBOX="$VAULT_PATH/HYPERFOCUS_ZONE/00-Inbox/OpenHuman-Feed"

mkdir -p "$VAULT_INBOX"

# Remove old symlink if it exists
if [ -L "$OPENHUMAN_MEMORY_DIR" ]; then
  rm "$OPENHUMAN_MEMORY_DIR"
  echo -e "${GREEN}✓${NC} Removed old symlink"
fi

# Create symlink
case "$OS_TYPE" in
  Windows)
    # Windows Git Bash / WSL doesn't support symlinks easily; use hardlink or just document the path
    echo -e "${YELLOW}⚠ Windows detected${NC} — symlink requires admin or WSL."
    echo "Instead, set this in your OpenHuman UI:"
    echo ""
    echo -e "  ${BLUE}Vault Path: $VAULT_INBOX${NC}"
    echo ""
    # Still try if we're in WSL
    ln -s "$VAULT_INBOX" "$OPENHUMAN_MEMORY_DIR" 2>/dev/null && echo -e "${GREEN}✓${NC} Symlink created (WSL)" || echo -e "${YELLOW}→${NC} Manual step: set vault path in OpenHuman UI"
    ;;
  *)
    ln -s "$VAULT_INBOX" "$OPENHUMAN_MEMORY_DIR"
    echo -e "${GREEN}✓${NC} Symlink created:"
    echo "   $OPENHUMAN_MEMORY_DIR → $VAULT_INBOX"
    ;;
esac

echo ""

# 6. Create Obsidian YAML frontmatter template
echo -e "${BLUE}Step 5: Create Obsidian template for OpenHuman notes${NC}"
echo ""

TEMPLATES_DIR="$VAULT_PATH/HYPERFOCUS_ZONE/99-Templates"
mkdir -p "$TEMPLATES_DIR"

cat > "$TEMPLATES_DIR/OpenHuman-Memory.md" << 'EOF'
---
created: {{date:YYYY-MM-DD}} {{time:HH:mm}}
source: OpenHuman
tags: [openhuman, memory, auto-sync]
status: inbox
priority: low
---

# {{title}}

**Source**: {{source}}  
**Synced**: {{date}}  

## Content

{{content}}

## Actions

- [ ] Review & categorize
- [ ] Link to related notes
- [ ] Archive when done
EOF

echo -e "${GREEN}✓${NC} Template created: ${YELLOW}$TEMPLATES_DIR/OpenHuman-Memory.md${NC}"
echo ""

# 7. Check if agentmemory is on the horizon
echo -e "${BLUE}Step 6: Future roadmap check${NC}"
echo ""
echo -e "OpenHuman's ${YELLOW}agentmemory${NC} backend is currently:"
echo -e "  Status: ${YELLOW}In Beta${NC} (tracked in GitHub issue #2620)"
echo -e "  When ready: Your .env will auto-enable it (no action needed)"
echo -e "  Progress: ${BLUE}https://github.com/tinyhumansai/openhuman/issues/2620${NC}"
echo ""
echo "Keep this file around — once agentmemory ships, re-run this installer"
echo "and it will automatically upgrade to the backend sync."
echo ""

# 8. Final checklist
echo -e "${BLUE}╔════════════════════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║  ✅ INSTALLATION COMPLETE                                      ║${NC}"
echo -e "${BLUE}╚════════════════════════════════════════════════════════════════╝${NC}"
echo ""
echo -e "${GREEN}Next steps:${NC}"
echo ""
echo "1. Install OpenHuman (if not already done):"
echo "   macOS:  ${YELLOW}brew install openhuman${NC}"
echo "   Linux:  ${YELLOW}cargo install openhuman${NC} (or apt/dnf/pacman)"
echo "   Win:    ${YELLOW}Download from https://openhuman.io${NC}"
echo ""
echo "2. Start OpenHuman:"
echo "   ${YELLOW}openhuman${NC}"
echo ""
echo "3. In OpenHuman UI, connect your integrations:"
echo "   → GitHub (one-click OAuth)"
echo "   → Gmail (if desired)"
echo "   → Slack (if desired)"
echo ""
echo "4. Wait 20 mins for first sync, then check your vault:"
echo "   ${BLUE}$VAULT_INBOX${NC}"
echo ""
echo "5. Notes will appear as:"
echo "   - GitHub issues → ${YELLOW}00-Inbox/OpenHuman-Feed/github-*.md${NC}"
echo "   - Slack messages → ${YELLOW}00-Inbox/OpenHuman-Feed/slack-*.md${NC}"
echo "   - Gmail threads → ${YELLOW}00-Inbox/OpenHuman-Feed/gmail-*.md${NC}"
echo ""
echo "🧠 Your brain is now the hub. Everything flows in, nothing gets lost."
echo ""
echo "Questions? Check out:"
echo "  - This repo: OPENHUMAN_INTEGRATION.md"
echo "  - OpenHuman docs: ${BLUE}https://docs.openhuman.io${NC}"
echo "  - GitHub issues: ${BLUE}https://github.com/tinyhumansai/openhuman${NC}"
echo ""
echo -e "${GREEN}🐶♾️ Nice one BROski! Brain sync incoming...${NC}"
