"""HYPER BRAIN v3.0 — Analytics Engine
Level 16 & 19 | Focus heatmaps, streaks, weekly reports, distraction patterns
"""
import json
import os
from datetime import datetime, timedelta
from pathlib import Path
from collections import defaultdict
from typing import List, Dict, Optional

VAULT_PATH = Path(os.environ.get("VAULT_PATH", "/vault"))
ANALYTICS_DIR = VAULT_PATH / "HYPERFOCUS_ZONE" / "Analytics"


class AnalyticsEngine:
    def __init__(self):
        ANALYTICS_DIR.mkdir(parents=True, exist_ok=True)
        self.sessions_file = ANALYTICS_DIR / "sessions.json"
        self.streaks_file = ANALYTICS_DIR / "streaks.json"
        self.heatmap_file = ANALYTICS_DIR / "heatmap.json"

    def load_sessions(self) -> List[dict]:
        if not self.sessions_file.exists():
            return []
        try:
            return json.loads(self.sessions_file.read_text())
        except Exception:
            return []

    def calculate_streak(self) -> dict:
        sessions = self.load_sessions()
        if not sessions:
            return {"current_streak": 0, "longest_streak": 0, "last_session": None}

        completed = [s for s in sessions if s.get("completed")]
        if not completed:
            return {"current_streak": 0, "longest_streak": 0, "last_session": None}

        # Group by date
        dates = sorted(set(
            s["started_at"][:10] for s in completed
        ), reverse=True)

        current_streak = 1
        longest_streak = 1
        temp_streak = 1

        for i in range(1, len(dates)):
            d1 = datetime.fromisoformat(dates[i - 1])
            d2 = datetime.fromisoformat(dates[i])
            if (d1 - d2).days == 1:
                temp_streak += 1
                longest_streak = max(longest_streak, temp_streak)
            else:
                temp_streak = 1

        # Check if streak is still active (last session today or yesterday)
        today = datetime.now().date()
        last_date = datetime.fromisoformat(dates[0]).date()
        if (today - last_date).days <= 1:
            current_streak = temp_streak
        else:
            current_streak = 0

        streak_data = {
            "current_streak": current_streak,
            "longest_streak": longest_streak,
            "last_session": dates[0] if dates else None,
            "streak_recovery_tokens": max(0, 3 - current_streak) if current_streak < 3 else 0
        }
        self.streaks_file.write_text(json.dumps(streak_data, indent=2))
        return streak_data

    def generate_heatmap(self, days: int = 30) -> dict:
        sessions = self.load_sessions()
        heatmap = defaultdict(int)

        cutoff = datetime.now() - timedelta(days=days)
        for s in sessions:
            try:
                date = datetime.fromisoformat(s["started_at"])
                if date >= cutoff and s.get("completed"):
                    hour = date.hour
                    day = date.strftime("%A")
                    heatmap[f"{day}_{hour:02d}:00"] += 1
            except Exception:
                continue

        heatmap_data = {
            "generated_at": datetime.now().isoformat(),
            "days_analysed": days,
            "peak_focus_times": sorted(
                heatmap.items(), key=lambda x: x[1], reverse=True
            )[:5],
            "full_heatmap": dict(heatmap)
        }
        self.heatmap_file.write_text(json.dumps(heatmap_data, indent=2))
        return heatmap_data

    def weekly_report(self) -> str:
        sessions = self.load_sessions()
        streak = self.calculate_streak()
        heatmap = self.generate_heatmap(7)

        week_ago = datetime.now() - timedelta(days=7)
        this_week = [s for s in sessions if
                     datetime.fromisoformat(s.get("started_at", "2000-01-01")) >= week_ago]

        completed = [s for s in this_week if s.get("completed")]
        total_minutes = sum(s.get("duration_minutes", 0) for s in completed)
        avg_distractions = (
            sum(s.get("distractions", 0) for s in completed) / len(completed)
            if completed else 0
        )

        peak = heatmap["peak_focus_times"][0][0] if heatmap["peak_focus_times"] else "N/A"

        report = f"""# 📊 Weekly Focus Report — {datetime.now().strftime('%Y-%m-%d')}

## Stats
- ✅ Sessions completed: {len(completed)}
- ⏱ Total focus time: {total_minutes} minutes
- 🔥 Current streak: {streak['current_streak']} days
- 🏆 Longest streak: {streak['longest_streak']} days
- 😵 Avg distractions/session: {avg_distractions:.1f}
- 🧠 Peak focus time: {peak}

## XP Summary
- Sessions this week: {len(this_week)} total, {len(completed)} completed
- Estimated XP earned: {len(completed) * 25}+

*Generated by HYPER BRAIN v3.0 Analytics Engine* 🧠⚡
"""
        report_file = ANALYTICS_DIR / f"weekly_report_{datetime.now().strftime('%Y-%m-%d')}.md"
        report_file.write_text(report)
        return report


if __name__ == "__main__":
    engine = AnalyticsEngine()
    print("🧠 Analytics Engine v3.0 running...")
    streak = engine.calculate_streak()
    print(f"Streak: {streak}")
    heatmap = engine.generate_heatmap()
    print(f"Peak focus times: {heatmap['peak_focus_times']}")
