"""HYPER BRAIN v3.0 — HyperSplit Task Decomposition
Level 17 | Recursive task decomposition with AI prioritisation + focus budgets
"""
import os
import json
from datetime import datetime
from pathlib import Path
from typing import List, Optional
from dataclasses import dataclass, field, asdict

VAULT_PATH = Path(os.environ.get("VAULT_PATH", "/vault"))
TASKS_DIR = VAULT_PATH / "HYPERFOCUS_ZONE" / "Tasks"


@dataclass
class SubTask:
    title: str
    estimated_minutes: int = 15
    difficulty: str = "easy"   # easy | medium | hard
    energy_required: int = 3   # 1-10
    completed: bool = False
    order: int = 0


@dataclass
class HyperTask:
    title: str
    description: str = ""
    priority: str = "medium"   # low | medium | high | hyperfocus
    sub_tasks: List[SubTask] = field(default_factory=list)
    created_at: str = field(default_factory=lambda: datetime.now().isoformat())
    total_minutes: int = 0
    energy_budget: int = 5


class HyperSplit:
    """Recursively decomposes tasks into ADHD-friendly micro-actions."""

    MAX_SUBTASK_MINUTES = 20  # Nothing over 20 mins — prevents overwhelm
    MIN_SUBTASK_MINUTES = 5

    def split(self, title: str, estimated_total_minutes: int,
              energy_level: int = 5, context: str = "") -> HyperTask:
        """Split a task into ADHD-friendly sub-tasks."""
        task = HyperTask(
            title=title,
            description=context,
            energy_budget=energy_level
        )

        sub_tasks = self._decompose(title, estimated_total_minutes, energy_level)
        task.sub_tasks = sub_tasks
        task.total_minutes = sum(s.estimated_minutes for s in sub_tasks)
        return task

    def _decompose(self, title: str, total_minutes: int,
                   energy: int) -> List[SubTask]:
        """Break total time into energy-appropriate chunks."""
        chunk_size = self._get_chunk_size(energy)
        num_chunks = max(1, total_minutes // chunk_size)
        remainder = total_minutes % chunk_size

        sub_tasks = []
        # First task is always the smallest — quick win to build momentum
        sub_tasks.append(SubTask(
            title=f"🚀 Quick win: Set up + define done for '{title}'",
            estimated_minutes=5,
            difficulty="easy",
            energy_required=2,
            order=0
        ))

        for i in range(num_chunks):
            sub_tasks.append(SubTask(
                title=f"⚡ Work block {i + 1}: {title}",
                estimated_minutes=chunk_size,
                difficulty=self._get_difficulty(energy),
                energy_required=energy,
                order=i + 1
            ))

        if remainder >= self.MIN_SUBTASK_MINUTES:
            sub_tasks.append(SubTask(
                title=f"🏁 Final push + review: {title}",
                estimated_minutes=remainder,
                difficulty="medium",
                energy_required=max(1, energy - 2),
                order=len(sub_tasks)
            ))

        # Always end with a celebrate/log step
        sub_tasks.append(SubTask(
            title=f"🎉 Mark done + log to vault: {title}",
            estimated_minutes=2,
            difficulty="easy",
            energy_required=1,
            order=len(sub_tasks)
        ))

        return sub_tasks

    def _get_chunk_size(self, energy: int) -> int:
        if energy <= 3:
            return 10  # Low energy — tiny chunks
        elif energy <= 6:
            return 15  # Normal — classic Pomodoro-lite
        else:
            return 20  # High energy — longer deep work

    def _get_difficulty(self, energy: int) -> str:
        if energy <= 3:
            return "easy"
        elif energy <= 6:
            return "medium"
        return "hard"

    def to_markdown(self, task: HyperTask) -> str:
        lines = [
            f"# 🧩 HyperSplit: {task.title}",
            f"> Created: {task.created_at[:10]} | Energy budget: {task.energy_budget}/10",
            f"> Total estimated time: {task.total_minutes} minutes",
            "",
            "## Sub-Tasks",
        ]
        for st in task.sub_tasks:
            check = "x" if st.completed else " "
            lines.append(
                f"- [{check}] {st.title} *(~{st.estimated_minutes}min, energy: {st.energy_required}/10)*"
            )
        lines.append("")
        lines.append("*Generated by HyperSplit v3.0 — HYPER BRAIN* 🧠⚡")
        return "\n".join(lines)

    def save_to_vault(self, task: HyperTask):
        TASKS_DIR.mkdir(parents=True, exist_ok=True)
        filename = f"hypersplit_{datetime.now().strftime('%Y%m%d_%H%M%S')}.md"
        filepath = TASKS_DIR / filename
        filepath.write_text(self.to_markdown(task))
        print(f"✅ Saved to vault: {filepath}")
        return filepath


if __name__ == "__main__":
    splitter = HyperSplit()
    task = splitter.split(
        title="Build the GitHub webhook integration",
        estimated_total_minutes=60,
        energy_level=7
    )
    print(splitter.to_markdown(task))
