"""HYPER BRAIN v3.0 — Morning Briefing AI
Level 13 | AI-powered daily briefing generator for ADHD brains
"""
import os
import json
from datetime import datetime, timedelta
from pathlib import Path
from typing import List, Optional

VAULT_PATH = Path(os.environ.get("VAULT_PATH", "/vault"))
BRIEFINGS_DIR = VAULT_PATH / "HYPERFOCUS_ZONE" / "Briefings"
ANALYTICS_DIR = VAULT_PATH / "HYPERFOCUS_ZONE" / "Analytics"


class MorningBriefingAI:
    """Generates a personalised, ADHD-friendly morning briefing from vault data."""

    def __init__(self):
        BRIEFINGS_DIR.mkdir(parents=True, exist_ok=True)

    def _load_json(self, filepath: Path) -> dict:
        if filepath.exists():
            try:
                return json.loads(filepath.read_text())
            except Exception:
                pass
        return {}

    def _get_open_tasks(self) -> List[str]:
        tasks = []
        tasks_dir = VAULT_PATH / "HYPERFOCUS_ZONE" / "Tasks"
        if not tasks_dir.exists():
            return tasks
        for f in sorted(tasks_dir.glob("*.md"), reverse=True)[:5]:
            try:
                content = f.read_text(encoding="utf-8", errors="ignore")
                # Find unchecked tasks
                for line in content.splitlines():
                    if "- [ ]" in line:
                        tasks.append(line.strip().replace("- [ ] ", ""))
            except Exception:
                continue
        return tasks[:5]  # Top 5 open tasks

    def _get_github_updates(self) -> List[str]:
        github_file = VAULT_PATH / "HYPERFOCUS_ZONE" / "GitHub" / "recent_activity.json"
        data = self._load_json(github_file)
        updates = []
        for item in data.get("items", [])[:3]:
            updates.append(f"{item.get('type', 'Update')}: {item.get('title', 'Unknown')}")
        return updates

    def _get_streak(self) -> dict:
        return self._load_json(ANALYTICS_DIR / "streaks.json")

    def generate(self, energy_level: int = 5, override_message: Optional[str] = None) -> str:
        now = datetime.now()
        date_str = now.strftime("%A, %d %B %Y")
        time_str = now.strftime("%H:%M")

        streak = self._get_streak()
        open_tasks = self._get_open_tasks()
        github_updates = self._get_github_updates()

        # Energy-based greeting
        if energy_level <= 3:
            greeting = "😴 Low energy today — that's okay. Let's start SMALL."
            focus_tip = "Pick ONE tiny task. Just one. The rest can wait."
            session_suggestion = "10-minute session → rest → 10-minute session"
        elif energy_level <= 6:
            greeting = "👋 Morning Bro! Steady energy. Let's build momentum."
            focus_tip = "Start with a quick win, then tackle your main task."
            session_suggestion = "25-minute Pomodoro → 5-min break → repeat"
        else:
            greeting = "⚡ HIGH ENERGY DETECTED! Let's go BROski♾️!"
            focus_tip = "This is your hyperfocus window — protect it!"
            session_suggestion = "45-minute deep work → 15-min break"

        # Streak message
        current_streak = streak.get("current_streak", 0)
        if current_streak >= 7:
            streak_msg = f"🔥 {current_streak}-day streak! You're on FIRE!"
        elif current_streak >= 3:
            streak_msg = f"⚡ {current_streak}-day streak! Keep it going!"
        elif current_streak == 0:
            streak_msg = "🌱 New day, fresh start. Build that streak!"
        else:
            streak_msg = f"🔥 {current_streak}-day streak started!"

        # Build briefing
        lines = [
            f"# 🧠 Morning Briefing — {date_str}",
            f"> Generated: {time_str} | Energy: {energy_level}/10",
            "",
            f"## {greeting}",
            "",
            f"**Focus tip:** {focus_tip}",
            f"**Session plan:** {session_suggestion}",
            f"**Streak:** {streak_msg}",
            "",
            "## 🎯 Top 3 Tasks Today",
        ]

        if open_tasks:
            for i, task in enumerate(open_tasks[:3], 1):
                lines.append(f"{i}. {task}")
        else:
            lines.append("No open tasks found — check your vault!")

        if github_updates:
            lines.extend(["", "## 🐙 GitHub Updates"])
            for update in github_updates:
                lines.append(f"- {update}")

        if override_message:
            lines.extend(["", f"## 📢 Special Message", override_message])

        lines.extend([
            "",
            "## 🚀 Launch Sequence",
            "1. Close all non-essential tabs",
            "2. Put on your focus playlist",
            "3. Start your first task above",
            "4. Log your session when done",
            "",
            "*Generated by Morning Briefing AI — HYPER BRAIN v3.0* 🧠⚡"
        ])

        briefing = "\n".join(lines)

        # Save to vault
        filename = f"briefing_{now.strftime('%Y-%m-%d')}.md"
        (BRIEFINGS_DIR / filename).write_text(briefing)

        return briefing


if __name__ == "__main__":
    ai = MorningBriefingAI()
    print(ai.generate(energy_level=7))
